### ISSUE TITLE
heap-buffer-overflow in parser.hpp:1538:21

### ISSUE THREAD

**Issue by andreafioraldi** [ToruNiina/toml11#164]
Hi,
I found this bug while fuzzing your library, commit 647381020ef04b5d41d540ec489eba45e82d90a7 that is the current master at the time of writing.
You can trigger it trying to parse this malformed toml `0={0=""` (MD17MD0iIg== in base64) with `toml::parse`.

This is the address sanitizer report:
```
==2998449==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000000017 at pc 0x0000005cf5d9 bp 0x7fffffff85f0 sp 0x7fffffff85e8
READ of size 1 at 0x602000000017 thread T0
    #0 0x5cf5d8 in toml::result<std::pair<toml::basic_value<toml::discard_comments, std::unordered_map, std::vector>::table_type, toml::detail::region>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > toml::detail::parse_inline_table<toml::basic_value<toml::discard_comments, std::unordered_map, std::vector> >(toml::detail::location&) /home/andrea/Desktop/toml11/./toml/parser.hpp:1538:21
    #1 0x53241e in toml::result<toml::basic_value<toml::discard_comments, std::unordered_map, std::vector>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > toml::detail::parse_value<toml::basic_value<toml::discard_comments, std::unordered_map, std::vector> >(toml::detail::location&) /home/andrea/Desktop/toml11/./toml/parser.hpp:1756:74
    #2 0x5218af in toml::result<std::pair<std::pair<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, toml::detail::region>, toml::basic_value<toml::discard_comments, std::unordered_map, std::vector> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > toml::detail::parse_key_value_pair<toml::basic_value<toml::discard_comments, std::unordered_map, std::vector> >(toml::detail::location&) /home/andrea/Desktop/toml11/./toml/parser.hpp:1101:16
    #3 0x4e3717 in toml::result<toml::basic_value<toml::discard_comments, std::unordered_map, std::vector>::table_type, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > toml::detail::parse_ml_table<toml::basic_value<toml::discard_comments, std::unordered_map, std::vector> >(toml::detail::location&) /home/andrea/Desktop/toml11/./toml/parser.hpp:1921:28
    #4 0x4d27ef in toml::result<toml::basic_value<toml::discard_comments, std::unordered_map, std::vector>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > toml::detail::parse_toml_file<toml::basic_value<toml::discard_comments, std::unordered_map, std::vector> >(toml::detail::location&) /home/andrea/Desktop/toml11/./toml/parser.hpp:2025:19
    #5 0x4cf7b0 in toml::basic_value<toml::discard_comments, std::unordered_map, std::vector> toml::parse<toml::discard_comments, std::unordered_map, std::vector>(std::istream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/andrea/Desktop/toml11/./toml/parser.hpp:2124:23
    #6 0x4ce3ef in LLVMFuzzerTestOneInput /home/andrea/Desktop/toml11/harness.cpp:10:5
    #7 0x4ce155 in ExecuteFilesOnyByOne /home/andrea/Desktop/AFLplusplus-online-data-feedback/utils/aflpp_driver/aflpp_driver.c:191:7
    #8 0x4cdfc4 in main /home/andrea/Desktop/AFLplusplus-online-data-feedback/utils/aflpp_driver/aflpp_driver.c
    #9 0x7ffff7a5e0b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16
    #10 0x41e76d in _start (/home/andrea/Desktop/toml11/harness_afl+0x41e76d)

0x602000000017 is located 0 bytes to the right of 7-byte region [0x602000000010,0x602000000017)
allocated by thread T0 here:
    #0 0x4cb34d in operator new(unsigned long) (/home/andrea/Desktop/toml11/harness_afl+0x4cb34d)
    #1 0x4cf30c in __gnu_cxx::new_allocator<char>::allocate(unsigned long, void const*) /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/ext/new_allocator.h:114:27
    #2 0x4cf30c in std::allocator_traits<std::allocator<char> >::allocate(std::allocator<char>&, unsigned long) /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/alloc_traits.h:444:20
    #3 0x4cf30c in std::_Vector_base<char, std::allocator<char> >::_M_allocate(unsigned long) /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_vector.h:343:20
    #4 0x4cf30c in std::_Vector_base<char, std::allocator<char> >::_M_create_storage(unsigned long) /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_vector.h:358:33
    #5 0x4cf30c in std::_Vector_base<char, std::allocator<char> >::_Vector_base(unsigned long, std::allocator<char> const&) /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_vector.h:302:9
    #6 0x4cf30c in std::vector<char, std::allocator<char> >::vector(unsigned long, std::allocator<char> const&) /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_vector.h:508:9
    #7 0x4cf30c in toml::basic_value<toml::discard_comments, std::unordered_map, std::vector> toml::parse<toml::discard_comments, std::unordered_map, std::vector>(std::istream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/andrea/Desktop/toml11/./toml/parser.hpp:2097:23
    #8 0x4ce3ef in LLVMFuzzerTestOneInput /home/andrea/Desktop/toml11/harness.cpp:10:5
    #9 0x4ce155 in ExecuteFilesOnyByOne /home/andrea/Desktop/AFLplusplus-online-data-feedback/utils/aflpp_driver/aflpp_driver.c:191:7

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/andrea/Desktop/toml11/./toml/parser.hpp:1538:21 in toml::result<std::pair<toml::basic_value<toml::discard_comments, std::unordered_map, std::vector>::table_type, toml::detail::region>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > toml::detail::parse_inline_table<toml::basic_value<toml::discard_comments, std::unordered_map, std::vector> >(toml::detail::location&)
Shadow bytes around the buggy address:
  0x0c047fff7fb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7fc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7fd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7fe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7ff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c047fff8000: fa fa[07]fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8010: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8020: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8030: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8040: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8050: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==2998449==ABORTING

```

**Comment by andreafioraldi** [comment]
If you want, I can open a PR with the fuzzing harness that I wrote and ask the guys at Google OSS-Fuzz to run a continuous fuzzing campaign for you, reporting all the bugs to you ofc in a private channel.

**Comment by skannan89** [comment]
@andreafioraldi Does this issue occur for valid toml too?

**Comment by ToruNiina** [comment]
Thank you @andreafioraldi for the report! And sorry for the late reply.
I think I fixed the problem. But there could be more potential bugs, so I'm glad if you make a pull req.

And, @skannan89, at least with [valid example files listed in Burntsushi/toml-test](https://github.com/BurntSushi/toml-test/tree/master/tests/valid), toml11 v3.7.0 does not have any problem with asan.

**Comment by andreafioraldi** [comment]
Hi,

> @andreafioraldi Does this issue occur for valid toml too?

I don't know and suppose not, but valid or not valid is not important when there is a memory corruption bug.
As it is unlikely that an user of your library validates the input before using the lib API a bug that can be triggered with an invalid file is as dangerous as a bug triggered with a valid file. The correct behaviour is to report an error (e.g. not valid input C++ exception), never memory corruption, it can hurt a lot the security of the users.

>  I think I fixed the problem. But there could be more potential bugs, so I'm glad if you make a pull req.

Ty for fixing it, I don't have time now to look at the code, but I will run another time my tool to seek for regressions in your fix if any and let you know.

> And, @skannan89, at least with valid example files listed in Burntsushi/toml-test, toml11 v3.7.0 does not have any problem with asan.

As I said, you should test the lib with invalid files too. A nice and robust way to do it automatically is Fuzz Testing and Google can run it for you for free (https://google.github.io/oss-fuzz/)

**Comment by andreafioraldi** [comment]
@ToruNiina the fix seems robust
